{% set name = "opentelemetry-semantic-conventions" %}
{% set version = "0.33b0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67d62461c87b683b958428ced79162ec4d567dabf30b050f270bbd01eff89ced

build:
  number: 4
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools <81
    - wheel
  run:
    - python
    - setuptools <81

test:
  source_files:
    - tests
  imports:
    - opentelemetry
    - opentelemetry.semconv
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-semantic-conventions
  summary: OpenTelemetry Python / Semantic Conventions
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source
    Observability framework for instrumenting, generating, collecting, and exporting
    telemetry data such as traces, metrics, logs. As an industry-standard
    it is natively supported by a number of vendors.
  doc_url: https://opentelemetry-python.readthedocs.io
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-semantic-conventions

extra:
  recipe-maintainers:
    - mariusvniekerk
