{% set name = "opentelemetry-semantic-conventions" %}
{% set version = "0.58b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 6bd46f51264279c433755767bb44ad00f1c9e2367e1b42af563372c5a6fa0c25


build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api 1.37.0
    - typing-extensions >=4.5.0

test:
  source_files:
    - tests
  imports:
    - opentelemetry
    - opentelemetry.semconv
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  summary: OpenTelemetry Python / Semantic Conventions
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-semantic-conventions
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://opentelemetry-python.readthedocs.io
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-semantic-conventions
  description: |
    OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source
    Observability framework for instrumenting, generating, collecting, and exporting
    telemetry data such as traces, metrics, logs. As an industry-standard
    it is natively supported by a number of vendors.

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - mariusvniekerk