{% set name = "opentelemetry-semantic-conventions" %}
{% set alt_name = name.replace('-','_') %}
{% set version = "0.45b0" %}
{% set sha256 = "7c84215a44ac846bc4b8e32d5e78935c5c43482e491812a0bb8aaf87e4d92118" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ alt_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - hatchling
  run:
    - python

test:
  imports:
    - opentelemetry
    - opentelemetry.semconv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python
  summary: OpenTelemetry Python / Semantic Conventions
  description: |
    OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source
    Observability framework for instrumenting, generating, collecting, and exporting
    telemetry data such as traces, metrics, logs. As an industry-standard
    it is natively supported by a number of vendors.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://opentelemetry-python.readthedocs.io
  doc_source_url: https://github.com/open-telemetry/opentelemetry-python
  dev_url: https://github.com/open-telemetry/opentelemetry-python

extra:
  recipe-maintainers:
    - mariusvniekerk
